# Generated by Django 5.0.6 on 2025-06-30 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=20, unique=True)),
                ('package_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('package_dimensions', models.CharField(blank=True, max_length=100, null=True)),
                ('package_type', models.CharField(default='Standard', max_length=50)),
                ('fragile', models.BooleanField(default=False)),
                ('requires_signature', models.BooleanField(default=False)),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('actual_delivery', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PICKED_UP_FROM_SELLER', 'Picked Up from Seller'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED_AT_RELAY', 'Arrived at Relay Point'), ('READY_FOR_PICKUP', 'Ready for Pickup'), ('PICKED_UP_BY_CONSUMER', 'Picked Up by Consumer'), ('DELIVERED', 'Delivered'), ('RETURNED', 'Returned'), ('LOST', 'Lost'), ('DAMAGED', 'Damaged')], default='CREATED', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_milestone', models.BooleanField(default=False)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_statuses', to='logistics.package')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=255)),
                ('to_location', models.CharField(max_length=255)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estimated_time_hours', models.IntegerField(blank=True, null=True)),
                ('route_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_wilaya', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_from', to='core.wilaya')),
                ('to_wilaya', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_to', to='core.wilaya')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='logistics.package')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('PUSH', 'Push Notification'), ('WHATSAPP', 'WhatsApp')], max_length=20)),
                ('recipient', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.BooleanField(default=False)),
                ('delivery_confirmation', models.DateTimeField(blank=True, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='logistics.package')),
            ],
        ),
        migrations.CreateModel(
            name='PackageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Package Created'), ('PICKED_UP', 'Picked Up'), ('SCANNED', 'Scanned'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED', 'Arrived'), ('READY', 'Ready for Pickup'), ('PICKED_UP_BY_CONSUMER', 'Picked Up by Consumer'), ('DELIVERED', 'Delivered'), ('RETURNED', 'Returned'), ('LOST', 'Lost'), ('DAMAGED', 'Damaged'), ('NOTIFICATION_SENT', 'Notification Sent'), ('STATUS_UPDATED', 'Status Updated')], max_length=30)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='logistics.package')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
