# Generated by Django 5.0.6 on 2025-06-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('VENDOR', 'Vendor'), ('RELAY_OPERATOR', 'Relay Operator')], default='VENDOR', max_length=20),
        ),
    ]
