# Generated by Django 5.0.6 on 2025-06-30 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelayPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('opening_hours', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('BLOCKED', 'Blocked')], default='PENDING', max_length=20)),
                ('earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('operator', models.OneToOneField(limit_choices_to={'role': 'RELAY_OPERATOR'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.wilaya')),
            ],
        ),
    ]
