# Generated by Django 5.0.6 on 2025-06-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relayapplication',
            name='admin_notes',
        ),
        migrations.RemoveField(
            model_name='relayapplication',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='relayapplication',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='relayapplication',
            name='reviewed_by',
        ),
        migrations.AddField(
            model_name='relayapplication',
            name='commerce_register',
            field=models.ImageField(blank=True, null=True, upload_to='commerce_registers/'),
        ),
        migrations.AddField(
            model_name='relayapplication',
            name='id_card',
            field=models.ImageField(blank=True, null=True, upload_to='id_cards/'),
        ),
        migrations.AddField(
            model_name='relayapplication',
            name='store_image',
            field=models.ImageField(blank=True, null=True, upload_to='store_images/'),
        ),
    ]
